version: '2.4'

services:

  eventstore:
    image: kurrentplatform/kurrentdb:26.1
    container_name: "cqrs-4-java-eventstore"
    ports:
      - "1113:1113"
      - "2113:2113"
    environment:
      KURRENTDB_MEM_DB: "true"
      KURRENTDB_RUN_PROJECTIONS: "all"
      KURRENTDB_INSECURE: "true"
      KURRENTDB_LOG: "/tmp/log-eventstore"
    networks:
      - cqrs-4-java-test

  mariadb:
    image: mariadb:11
    container_name: "cqrs-4-java-mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: xyz
      MYSQL_DATABASE: testdb
      MYSQL_USER: mary
      MYSQL_PASSWORD: abc
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    networks:
      - cqrs-4-java-test

networks:
  cqrs-4-java-test:
    name: cqrs-4-java-test
